---
- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - mariadb

- name: Remove all anonymous users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_password }}"
  tags:
    - mariadb

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_password }}"
  tags:
    - mariadb

- name: Edit my.cnf
  blockinfile:
    path: "/etc/mysql/my.cnf"
    block: |
      [mysqld]
      bind-address = 127.0.0.1
  tags:
    - mariadb
    - security
    - bind-localhost
  notify: Restart MariaDB (Debian)
