- name: Setting the root password
  mysql_user:
    name: root
    password: "{{ mariadb['password']['new'] }}"
    login_user: root
    login_password: "{{ mariadb['password']['old'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
  - mariadb

- name: Deleting all anonymous users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mariadb['password']['new'] }}"
  tags:
  - mariadb

- name: Deleting the test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb['password']['new'] }}"
  tags:
  - mariadb

- name: Prohibiting connections to the DBMS from the outside
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      bind-address = 127.0.0.1
  tags:
  - mariadb
  - security
  - bind-localhost
  notify: Restart MariaDB (Debian)
