galaxy_info:
  author: vitkuz573
  description: fail2ban for Linux
  license: license (BSD, MIT)
  min_ansible_version: 2.10
  platforms:
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - fail2ban

dependencies: []
