---
- name: Set default policy
  ufw:
    policy: deny
  tags:
    - ufw

- name: Deny access to Apache port
  ufw:
    rule: deny
    port: "{{ apache_port }}"
    proto: tcp
  tags:
    - ufw
    - security
    - block_apache_port

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: "OpenSSH"
  tags:
    - ufw

- name: Allow Nginx HTTP
  ufw:
    rule: allow
    name: "Nginx HTTP"
  tags:
    - ufw
  when: https_enabled == "no"

- name: Allow Nginx Full
  ufw:
    rule: allow
    name: "Nginx Full"
  tags:
    - ufw
  when: https_enabled == "yes"

- name: Allow Apache
  ufw:
    rule: allow
    name: "WWW"
  tags:
    - ufw

- name: Enable UFW
  ufw:
    state: enabled
  tags:
    - ufw
