- name: Setting the default policy
  ufw:
    policy: deny
  when: firewall['name'] == "ufw"
  tags:
  - ufw

- name: Blocking access to the Apache port
  ufw:
    rule: deny
    port: "{{ apache['port'] }}"
    proto: tcp
  when: firewall['name'] == "ufw"
  tags:
  - ufw
  - security
  - block_apache_port

- name: Allow SSH access
  ufw:
    rule: allow
    name: OpenSSH
  when: firewall['name'] == "ufw" and knockd['install'] == "false"
  tags:
  - ufw

- name: Allowing HTTP traffic
  ufw:
    rule: allow
    name: WWW
  when: firewall['name'] == "ufw" and https['enable'] == "false"
  tags:
  - ufw

- name: Allowing HTTP and HTTPS traffic
  ufw:
    rule: allow
    name: WWW Full
  when: firewall['name'] == "ufw" and https['enable'] == "true"
  tags:
  - ufw

- name: Allowing Apache
  ufw:
    rule: allow
    name: WWW
  when: firewall['name'] == "ufw"
  tags:
  - ufw

- name: Enabling UFW
  ufw:
    state: enabled
  when: firewall['name'] == "ufw"
  tags:
  - ufw
