---
- name: Setting the default policy
  ufw:
    policy: deny
  tags:
    - ufw

- name: Blocking access to the Apache port
  ufw:
    rule: deny
    port: "{{ apache_port }}"
    proto: tcp
  tags:
    - ufw
    - security
    - block_apache_port

- name: Allow SSH access
  ufw:
    rule: allow
    name: "OpenSSH"
  tags:
    - ufw
  when: knockd_install != "yes"

- name: Allowing HTTP traffic (Nginx)
  ufw:
    rule: allow
    name: "Nginx HTTP"
  tags:
    - ufw
  when: https_enabled == "no"

- name: Allowing HTTP and HTTPS traffic (Nginx)
  ufw:
    rule: allow
    name: "Nginx Full"
  tags:
    - ufw
  when: https_enabled == "yes"

- name: Allowing Apache
  ufw:
    rule: allow
    name: "WWW"
  tags:
    - ufw

- name: Enabling UFW
  ufw:
    state: enabled
  tags:
    - ufw
