repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: fix-byte-order-marker

- repo: https://github.com/ansible/ansible-lint.git
  rev: v5.0.0a2
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.0
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    entry: yamllint --strict

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.0.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/lovesegfault/beautysh.git
  rev: 6.0.1
  hooks:
  - id: beautysh
