repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-byte-order-marker

-   repo: https://github.com/ansible-community/ansible-lint.git
    rev: v4.1.0
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
    -   id: yamllint
        args: [-c=.yamllint]
