- hosts: debian
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root
  vars_files:
  - ./group_vars/vars.yml
  - ./host_vars/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.yml
  roles:
  - pre_transaction
  - apache
  - phpfpm
  - mod_fastcgi
  - mod_remoteip
  - nginx
  - letsencrypt
  - self_signed_certificate
  - mariadb
  - mysql
  - postgresql
  - phpmyadmin
  - pgadmin
  - knockd
  - sftp
  - ufw
  - firewalld
  - sshd
  - post_transaction
