---
- hosts: debian
  gather_facts: yes
  vars_files:
    - ./group_vars/vars.yml
    - ./host_vars/{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.yml
  roles:
    - misc
    - apache
    - php-fpm
    - mod_fastcgi
    - mod_remoteip
    - nginx
    - mariadb
    - phpmyadmin
    - knockd
    - sftp
    - ufw
