---
galaxy_info:
  author: vitkuz573
  description: Nginx for Linux
  license: license (BSD, MIT)
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - web
    - nginx
    - webserver

dependencies: []
