- name: Installing MariaDB
  apt:
    pkg:
    - mariadb-server
    - python3-pymysql
  when: dbms['install'] == "true" and dbms['name'] == "mariadb"
  tags:
  - mariadb

- name: Installing PyMySQL
  pip:
    name: pymysql
    executable: pip3
  when: dbms['install'] == "true" and dbms['name'] == "mariadb"
  tags:
  - mariadb
