- name: Installing MariaDB
  apt:
    pkg:
    - mariadb-server
    - python3-pymysql
  tags:
  - mariadb

- name: Installing PyMySQL
  pip:
    name: pymysql
    executable: pip3
  tags:
  - mariadb
