- name: Changing the port in ports.conf
  lineinfile:
    dest: /etc/apache2/ports.conf
    regexp: ^#?Listen
    line: Listen {{ apache['port'] }}

- name: Changing the port in 000-default.conf
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: ^#?<VirtualHost
    line: <VirtualHost *:{{ apache['port'] }}>

- name: Enabling mod_actions
  apache2_module:
    name: actions
    state: present

- name: Checking for the existence of an available host
  stat:
    path: /etc/apache2/sites-available/{{ domain['name'] }}.conf
  register: available_host_details

- name: Creating a virtual host
  template:
    src: templates/apache.conf.j2
    dest: /etc/apache2/sites-available/{{ domain['name'] }}.conf
    mode: 0644
  when: not available_host_details.stat.exists

- name: Creating a directory for the virtual host
  file:
    path: /var/www/{{ domain['name'] }}/public
    mode: 0755
    state: directory

- name: Generating index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ domain['name'] }}/public/index.html
    mode: 0644
  tags:
  - gen_index

- name: Checking for the existence of an enabled host
  stat:
    path: /etc/apache2/sites-enabled/{{ domain['name'] }}.conf
  register: enable_host_details

- name: Enabling the virtual host
  command: sudo a2ensite {{ domain['name'] }}
  when: not enable_host_details.stat.exists

- name: Hiding the Apache version
  blockinfile:
    path: /etc/apache2/apache2.conf
    block: |
      ServerSignature Off
      ServerTokens Prod
  tags:
  - security
  - hide_apache_version
  notify: Restart Apache (Debian)
