- name: Installing the necessary PHP extensions
  apt:
    pkg:
    - php{{ php['version'] }}-mysql
    - php{{ php['version'] }}-mbstring
  when: phpmyadmin['install'] == "true"
  tags:
  - phpmyadmin

- name: Installing phpMyAdmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin['version'] }}/phpMyAdmin-{{ phpmyadmin['version'] }}-all-languages.zip
    dest: /var/www/{{ domain['name'] }}/public/
    remote_src: true
  when: phpmyadmin['install'] == "true"
  tags:
  - phpmyadmin

- name: Checking the phpMyAdmin directory for existence
  stat:
    path: /var/www/{{ domain['name'] }}/public/phpmyadmin
  register: phpmyadmin_details
  when: phpmyadmin['install'] == "true"
  tags:
  - phpmyadmin

- name: Renaming the phpMyAdmin directory
  copy:
    src: /var/www/{{ domain['name'] }}/public/phpMyAdmin-{{ phpmyadmin['version'] }}-all-languages/
    dest: /var/www/{{ domain['name'] }}/public/phpmyadmin/
    remote_src: true
    mode: 0755
  when: phpmyadmin['install'] == "true" and not phpmyadmin_details.stat.exists
  tags:
  - phpmyadmin
