- name: Creating an sftp group
  group:
    name: sftpg
  when: sftp['configure'] == "yes"
  tags:
  - sftp

- name: Creating an sftp user
  user:
    name: "{{ sftp['credentials']['user'] }}"
    password: "{{ sftp['credentials']['password'] | password_hash('sha512') }}"
    group: sftpg
  when: sftp['configure'] == "yes"
  tags:
  - sftp

- name: Checking the existence of the sftp root directory
  stat:
    path: "{{ sftp['root'] }}"
  register: sftp_root_dir_details
  when: sftp['configure'] == "yes"
  tags:
  - sftp

- name: Creating the sftp root directory
  file:
    path: "{{ sftp['root'] }}"
    mode: 0755
    state: directory
  when: sftp['configure'] == "yes" and not sftp_root_dir_details.stat.exists
  tags:
  - sftp

- name: Checking the existence of the sftp user directory
  stat:
    path: "{{ sftp['root'] }}"
  register: sftp_user_dir_details
  when: sftp['configure'] == "yes"
  tags:
  - sftp

- name: Creating a user sftp directory
  file:
    path: "{{ sftp['root'] }}/{{ sftp['credentials']['user'] }}"
    owner: root
    group: sftpg
    mode: 0755
    state: directory
  when: sftp['configure'] == "yes" and not sftp_user_dir_details.stat.exists
  tags:
  - sftp

- name: Checking the existence of the upload directory
  stat:
    path: "{{ sftp['root'] }}"
  register: upload_dir_details
  when: sftp['configure'] == "yes"
  tags:
  - sftp

- name: Creating an upload directory
  file:
    path: "{{ sftp['root'] }}/{{ sftp['credentials']['user'] }}/upload"
    owner: "{{ sftp['credentials']['user'] }}"
    group: sftpg
    mode: 0755
    state: directory
  when: sftp['configure'] == "yes" and not upload_dir_details.stat.exists
  tags:
  - sftp

- name: Setting up sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Group sftpg
      ChrootDirectory "{{ sftp['root'] }}/%u"
      ForceCommand internal-sftp
  when: sftp['configure'] == "yes"
  tags:
  - sftp
  notify: Restart SSH (Debian)
