- name: Enabling knockd
  copy:
    src: files/knockd
    dest: /etc/default/knockd
    mode: 0644
  when: knockd['install'] == "true"
  tags:
  - knockd

- name: Setting up knockd
  template:
    src: templates/knockd.conf.j2
    dest: /etc/knockd.conf
    mode: 0644
  when: knockd['install'] == "true"
  notify: Restart Knockd (Debian)
  tags:
  - knockd
