- name: Installing requirements
  apt:
    pkg:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release

- name: Adding nginx repository
  template:
    src: templates/nginx.list.j2
    dest: /etc/apt/sources.list.d/nginx.list
    mode: 0644

- name: Adding nginx key
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Installing Nginx
  apt:
    update_cache: true
    pkg:
    - nginx
