---
galaxy_info:
  author: vitkuz573
  description: MariaDB for Linux
  license: license (BSD, MIT)
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - web
    - database
    - mysql
    - mariadb

dependencies: []
