- name: Setting the root password
  mysql_user:
    name: root
    password: "{{ dbms['credentials']['password']['new'] }}"
    login_user: root
    login_password: "{{ dbms['credentials']['password']['old'] }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: dbms['install'] == "true" and dbms['name'] == "mysql"
  tags:
  - mysql

- name: Deleting all anonymous users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ dbms['credentials']['password']['new'] }}"
  when: dbms['install'] == "true" and dbms['name'] == "mysql"
  tags:
  - mysql

- name: Deleting the test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ dbms['credentials']['password']['new'] }}"
  when: dbms['install'] == "true" and dbms['name'] == "mysql"
  tags:
  - mysql

- name: Prohibiting connections to the DBMS from the outside
  blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      bind-address = 127.0.0.1
  when: dbms['install'] == "true" and dbms['name'] == "mysql"
  tags:
  - mysql
  - security
  - bind-localhost
  notify: Restart MySQL (Debian)
