- name: Setting hostname
  hostname:
    name: "{{ host['name'] }}"

- name: Generating index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/{{ domain['name'] }}/public/index.html
    mode: 0644
  tags:
  - gen_index

- name: Creating a script to connect to SSH
  template:
    src: templates/ssh_knock.sh.j2
    dest: /home/$USER/ssh_knock_{{ domain['name'] }}.sh
    mode: 0644
  when: knockd['install'] == "true"
  delegate_to: 127.0.0.1
  tags:
  - knockd

- name: Changing permissions for knocking script
  file:
    dest: /home/$USER/ssh_knock_{{ domain['name'] }}.sh
    mode: a+x
  when: knockd['install'] == "true"
  delegate_to: 127.0.0.1
  tags:
  - knockd
