- name: Blocking access to the Apache port
  ansible.posix.firewalld:
    port: "{{ apache['port'] }}"
    permanent: true
    state: disabled
  when: firewall['name'] == "firewalld"
  tags:
  - firewalld
  - security
  - block_apache_port

- name: Allow SSH access
  ansible.posix.firewalld:
    service: ssh
    zone: public
    permanent: true
    state: present
  when: firewall['name'] == "firewalld"
  tags:
  - firewalld

- name: Allowing HTTP traffic
  ansible.posix.firewalld:
    service: http
    zone: public
    permanent: true
    state: present
  when: firewall['name'] == "firewalld"
  tags:
  - firewalld

- name: Allowing HTTPS traffic
  ansible.posix.firewalld:
    service: https
    zone: public
    permanent: true
    state: present
  when: firewall['name'] == "firewalld" and https['enable'] == "true"
  notify: Restart Firewalld (Debian)
  tags:
  - firewalld
