- name: Installing the required deb packages
  apt:
    update_cache: true
    pkg:
    - sudo
    - wget
    - pwgen
    - unzip
    - net-tools
    - python3-apt
    - python3-pip
    - python3-passlib
    - apt-transport-https
    - ca-certificates

- name: Installing the required python packages
  pip:
    name: setuptools
    executable: pip3
