- name: Setting up Nginx (without HTTPS)
  copy:
    src: files/nginx_http.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  when: https['enable'] == "no"

- name: Setting up Nginx (with HTTPS)
  copy:
    src: files/nginx_https.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
  when: https['enable'] == "yes"

- name: Checking the ansiblewebserver.configs directory for existence
  stat:
    path: /etc/nginx/ansiblewebserver.configs
  register: ansiblewebserver_configs_details

- name: Creating a directory for additional configuration files
  file:
    path: /etc/nginx/ansiblewebserver.configs
    mode: 0755
    state: directory
  when: not ansiblewebserver_configs_details.stat.exists

- name: Copying security.conf (without HTTPS)
  copy:
    src: files/security_http.conf
    dest: /etc/nginx/ansiblewebserver.configs/security.conf
    mode: 0644
  when: https['enable'] == "no"

- name: Copying security.conf (with HTTPS)
  copy:
    src: files/security_https.conf
    dest: /etc/nginx/ansiblewebserver.configs/security.conf
    mode: 0644
  when: https['enable'] == "yes"

- name: Copying letsencrypt.conf
  copy:
    src: files/letsencrypt.conf
    dest: /etc/nginx/ansiblewebserver.configs/letsencrypt.conf
    mode: 0644
  when: https['enable'] == "yes" and https['option'] == "2"

- name: Checking dhparam.pem file for existence
  stat:
    path: /etc/nginx/dhparam.pem
  register: dhparam_details

- name: Generation of Diffie-Hellman parameters
  openssl_dhparam:
    path: /etc/nginx/dhparam.pem
    size: 4096
    force: true
  when: https['enable'] == "yes" and not dhparam_details.stat.exists

- name: Copying general.conf
  copy:
    src: files/general.conf
    dest: /etc/nginx/ansiblewebserver.configs/general.conf
    mode: 0644

- name: Copying proxy.conf
  copy:
    src: files/proxy.conf
    dest: /etc/nginx/ansiblewebserver.configs/proxy.conf
    mode: 0644

- name: Creating a host (without HTTPS)
  template:
    src: templates/domain_http.conf.j2
    dest: /etc/nginx/sites-available/{{ domain['name'] }}.conf
    mode: 0644
  when: https['enable'] == "no"

- name: Creating a host (with HTTPS) (option 1)
  template:
    src: templates/domain_https.conf.j2
    dest: /etc/nginx/sites-available/{{ domain['name'] }}.conf
    mode: 0644
  when: https['enable'] == "yes" and https['option'] == "1"

- name: Creating a host (with HTTPS) (option 2)
  template:
    src: templates/domain_letsencrypt.conf.j2
    dest: /etc/nginx/sites-available/{{ domain['name'] }}.conf
    mode: 0644
  when: https['enable'] == "yes" and https['option'] == "2"

- name: Enabling the host
  file:
    src: /etc/nginx/sites-available/{{ domain['name'] }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain['name'] }}.conf
    state: link
    force: true
  notify: Restart Nginx (Debian)
